services:
  # Override Open WebUI for development
  open-webui:
    environment:
      - WEBUI_AUTH=False  # Disable auth for development
      - WEBUI_NAME=AI Stack DEV
    
  # Override n8n for development
  n8n:
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false  # Disable auth for development
    
  # Add development tools
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - ai-stack

volumes:
  portainer-data:
